version: '3.8'

services:
  web:
    container_name: web
    build: app
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/static
    expose:
      - 8000
    env_file:
      - app/.env
    depends_on:
      - db
      - redis

  db:
    container_name: db
    image: postgres:13.0-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - ./.env

  nginx:
    container_name: nginx
    build: nginx
    volumes:
      - static_volume:/usr/src/app/static
    ports:
      - 80:80
    depends_on:
      - web

  redis:
    container_name: redis
    image: redis
    expose:
      - 6379

volumes:
  postgres_volume:
  static_volume:
